import {Layout} from 'modules/layout/Layout';

export const App = () => {
  return (
    <Layout>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
      <div>App</div>
    </Layout>
  );
};
